// This file is generated by FlutterFire CLI.
// Replace with actual Firebase configuration after running:
// flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgOf3h6e7HW-dJNiD_FyACYGBLbeubFks',
    appId: '1:428576928220:web:8fb9513d11fe2c08375f19',
    messagingSenderId: '428576928220',
    projectId: 'swift-cv-app',
    authDomain: 'swift-cv-app.firebaseapp.com',
    storageBucket: 'swift-cv-app.firebasestorage.app',
    measurementId: 'G-YF14WF34B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgOf3h6e7HW-dJNiD_FyACYGBLbeubFks',
    appId: '1:428576928220:android:be7bb3e15df9542e375f19',
    messagingSenderId: '428576928220',
    projectId: 'swift-cv-app',
    storageBucket: 'swift-cv-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgOf3h6e7HW-dJNiD_FyACYGBLbeubFks',
    appId: '1:428576928220:ios:8fb9513d11fe2c08375f19',
    messagingSenderId: '428576928220',
    projectId: 'swift-cv-app',
    storageBucket: 'swift-cv-app.firebasestorage.app',
    iosBundleId: 'com.example.swiftCv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgOf3h6e7HW-dJNiD_FyACYGBLbeubFks',
    appId: '1:428576928220:macos:8fb9513d11fe2c08375f19',
    messagingSenderId: '428576928220',
    projectId: 'swift-cv-app',
    storageBucket: 'swift-cv-app.firebasestorage.app',
    iosBundleId: 'com.example.swiftCv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgOf3h6e7HW-dJNiD_FyACYGBLbeubFks',
    appId: '1:428576928220:windows:8fb9513d11fe2c08375f19',
    messagingSenderId: '428576928220',
    projectId: 'swift-cv-app',
    storageBucket: 'swift-cv-app.firebasestorage.app',
  );
}
